#spring:
#  data:
#    mongodb:
#      uri: ${MONGODB_URI}
#      auto-index-creation: true
#  application:
#    name: Journal App
#
#logging:
#  level:
#    org.springframework.security: DEBUG
#
#server:
#  port: 8081
#  servlet:
#    context-path: /journal
