spring:
  application:
    name: Journal App


server:
  port: 8081
  servlet:
    context-path: /journal

logging:
  level:
    xyz:
      znet:
        journalapp:
          service:
            userService: ERROR
#can use root: off as well below level
